sdk/package.json
sdk/src/artifacts/whirlpool.json
sdk/src/artifacts/whirlpool.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/instructions/decrease-liquidity-ix.ts
sdk/src/instructions/increase-liquidity-ix.ts
sdk/src/quotes/public/decrease-liquidity-quote.ts
sdk/src/quotes/public/increase-liquidity-quote.ts
yarn.lock

- Add tokenEst(imates) to the increase/decrease liquidity quotes
- Add group token resolution to minimize RPC calls when resolving ATAs
Token estimates - What we can expect the resulting token to be at this given time / on-chain data
Token min - The minimum expected amount of token received / sent given the estimate and slippage

Add token estimates for liquidity quotes, group token resolution

---

programs/whirlpool/src/lib.rs
sdk/src/artifacts/whirlpool.json
sdk/src/artifacts/whirlpool.ts

Noticed inconsistent variable naming when working with the IDL. This makes the argument names consistent between `swap.rs` and `lib.rs` and regenerates the IDL.

Swap argument name consistency between lib.rs and swap.rs

---

sdk/src/utils/public/pool-utils.ts
sdk/tests/utils/pool-utils.test.ts

**Background**
The Whirlpools smart contract enforces a strict ordering of pool token mints for `token_a` and `token_b` to guarantee unique pools. This ordering does not represent a `base / quote` currency pair.
**Changes**
This PR adds a helper method to determine a `base / quote` currency ordering that prioritizes USD stable coins followed by SOL and its variants.

Adding toBaseQuoteOrder method to pool-utils

---

programs/whirlpool/src/util/token.rs

_I'm not sure if you are accepting PRs from outside the project but I noticed this and I thought I raise it._
[`to_account_info()`](https://github.com/project-serum/anchor/blob/5194de04b1d2446730d42f75e875f3b2facca312/lang/src/lib.rs#L133) helpfully (?) performs a `clone()` already so the second cloning is not necessary.
`cargo test` runs fine but can't seem to get `anchor test` going. Rolled back to Anchor 0.20.1 and added some missing dependencies like `@orca-so/sdk` but no luck. I was hoping there would be a GitHub Action for it but doesn't look like it.

fix(token): remove double clone()ing from CPI calls

---

sdk/src/quotes/public/swap-quote.ts
sdk/src/utils/public/tick-utils.ts
sdk/tests/integration/swap.test.ts

Previous swapQuote function is pretty difficult to use. Making some modifications to help users call swap quotes. This is a breaking change to the swapQuote's parameters. When we release, we have to bump to v0.2.0
- `swapQuoteByInputToken` as a convenience method to help users fetch the necessary information to perform the swap quote
- `swapQuoteWithParams` for the more advanced users who have previously fetched the data they need to perform the swap quote

[v0.2.0] Refactor swapQuote functions

---

sdk/src/quotes/public/swap-quote.ts
sdk/src/utils/public/tick-utils.ts
sdk/tests/integration/swap.test.ts

- Refactor swapQuoteByInputToken as a convenience method to help users fetch the necessary information to perform the swap quote
- Add swapQuoteWithParams for the more advanced users who have previously fetched the data they need to perform the swap quote

[v0.2.0] Refactor swapQuote functions (#20)

---

sdk/src/impl/position-impl.ts
sdk/src/whirlpool-client.ts
sdk/tests/sdk/whirlpools/position-impl.test.ts
sdk/tests/sdk/whirlpools/whirlpool-impl.test.ts
sdk/tests/utils/test-builders.ts

- Add an option to auto-generate ATA to perform increase_liquidity for Whirlpool's position class
NOTES:
- Modified the position impl test to call increase_liquidity using tokens from another wallet & to auto-gen the ATA
- Performed a test on the SOL/USDC pool to confirm that resolveATA works (because SOL always generates a new ATA to transfer)
- Ran the whole test suite again to confirm that the test-builder change didn't break any tests.

Add resolveATA option for Position's increase_liquidity

---

sdk/src/errors/errors.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/quotes/public/swap-quote.ts
sdk/src/quotes/swap/swap-manager.ts
sdk/src/quotes/swap/swap-quote-impl.ts
sdk/src/quotes/swap/tick-array-index.ts
sdk/src/quotes/swap/tick-array-sequence.ts
sdk/src/types/public/client-types.ts
sdk/src/types/public/constants.ts
sdk/src/utils/math/bit-math.ts
sdk/src/utils/math/swap-math.ts
sdk/src/utils/math/token-math.ts
sdk/src/utils/position-util.ts
sdk/src/utils/public/index.ts
sdk/src/utils/public/pool-utils.ts
sdk/src/utils/public/price-math.ts
sdk/src/utils/public/swap-utils.ts
sdk/src/utils/public/tick-utils.ts
sdk/tests/integration/swap.test.ts
sdk/tests/sdk/whirlpools/swap/swap-array.test.ts
sdk/tests/sdk/whirlpools/swap/swap-traverse.test.ts
sdk/tests/sdk/whirlpools/utils/pool-utils.test.ts
sdk/tests/sdk/whirlpools/utils/swap-utils.test.ts
sdk/tests/sdk/whirlpools/utils/tick-array-sequence.test.ts
sdk/tests/utils/assert.ts
sdk/tests/utils/init-utils.ts
sdk/tests/utils/swap-test-utils.ts
sdk/tests/utils/testDataTypes.ts
sdk/tests/utils/token.ts
sdk/tests/utils/whirlpools-test-utils.ts

- More accurate quote values - ported the swap logic from contract & add comprehensive unit-test suite to confirm quote values are identical to contract results
- More info available in quote - endTickIndex, sqrtPrice, feeAmount etc...
- Additional swapQuoteFromOutputToken to allow users to ask for a quote (and swap input parameters) based on the desired receive amount
- Bug fix on TickArray calculation that led to the annoying 0x1787 (InvalidTickArraySequence) error
- Addresses all errors in the old-swap quote where it fails to traverse tick-arrays in many cases
- Bug fix on WhirlpoolClient.swap where it incorrectly uses the quote.estimated values rather than the user defined tokenAmount value
- Parameter changes for the SwapQuote functions - `swapQuoteByInputToken`, …

[SDK] Refactoring swap-quote 

---

sdk/src/impl/whirlpool-impl.ts
sdk/src/instructions/decrease-liquidity-ix.ts
sdk/src/instructions/increase-liquidity-ix.ts
sdk/src/quotes/public/decrease-liquidity-quote.ts
sdk/src/quotes/public/swap-quote.ts
sdk/src/quotes/swap/swap-manager.ts
sdk/src/quotes/swap/swap-quote-impl.ts
sdk/src/utils/public/pool-utils.ts
sdk/tests/integration/collect_fees.test.ts
sdk/tests/integration/collect_protocol_fees.test.ts
sdk/tests/integration/decrease_liquidity.test.ts
sdk/tests/integration/increase_liquidity.test.ts
sdk/tests/integration/swap.test.ts
sdk/tests/integration/update_fees_and_rewards.test.ts
sdk/tests/sdk/whirlpools/swap/swap-array.test.ts
sdk/tests/sdk/whirlpools/swap/swap-traverse.test.ts
sdk/tests/utils/init-utils.ts
sdk/tests/utils/swap-test-utils.ts
sdk/tests/utils/test-consts.ts

- Change type of variables handling liquidity from u64 to BN
- Fix: removing "async" keyword from describe. test must be defined synchronously.
- Fix: using BN to calculate the max value of u64 (test-constants.ts)
- Fix: adding "await" to wait transaction completion (swap-test-utils.ts)
- Change type of variables handling sqrtPrice from u64 to BN
- Refactor: changing argument name of getTokenAmountsFromLiquidity
to clarify required price is sqrtPrice
anchor test passes all unit-tests

Change data type for liquidity and sqrtPrice to BN

---

sdk/src/impl/util.ts
sdk/src/impl/whirlpool-client-impl.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/types/public/client-types.ts
sdk/src/whirlpool-client.ts

Implementing a `getPools` method on the WhirlpoolClient for batch fetching pools.
This change also adds fetching onchain data for token accounts for vaults (including reward vaults).
These fields were provided by the old SDK, and it feels like they also belong in the new SDK rather than interacting with the web3.js client after retrieving whirlpools.

Implement batch getPools method

---

sdk/tests/utils/test-consts.ts

there's is a small typo in the definition of the `MAX_U64` constant, instead of `2^(64-1)` it should be `2^64-1`
https://github.com/orca-so/whirlpools/blob/8fc92ea1afe6b46404a3d1097525a5c92933211d/sdk/tests/utils/test-consts.ts#L10
probably not a big issue, but running some numbers I couldn't reproduce some of your test results and it took me some time until i realize this was the cause

fix sdk test MAX_U64 definition 

---

README.md

Old (not working): https://project-serum.github.io/anchor/getting-started/installation.html#install-rust
New (working): https://book.anchor-lang.com/getting_started/installation.html#anchor

update anchor installation link

---

programs/whirlpool/src/state/whirlpool.rs

The comment is incorrect. This is described correctly in the Developer Portal, so this will sync up with the documentation.

protocol_fee_rate comment

---

sdk/package.json
sdk/src/errors/errors.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/instructions/swap-ix.ts
sdk/src/quotes/public/dev-fee-swap-quote.ts
sdk/src/quotes/public/swap-quote.ts
sdk/src/quotes/swap/swap-quote-utils.ts
sdk/src/whirlpool-client.ts
sdk/tests/sdk/whirlpools/swap/swap-dev-fee.test.ts
sdk/tests/utils/assert.ts
sdk/tests/utils/init-utils.ts
sdk/tests/utils/swap-test-utils.ts
sdk/tests/utils/test-builders.ts
sdk/tests/utils/token.ts
yarn.lock

- Add a new `swapWithDevFees` function in the `Whirlpool` client class
- Add new `swapQuoteByInputTokenWithDevFees` quote function
Allow developers to take a percentage of a swap prior to executing the swap instruction.
https://github.com/orca-so/orca-sdks/pull/10
- Not a smart-contract integration
- Pending testing

Allow developers to take additional fees from a swap

---

sdk/src/quotes/public/index.ts

I noticed that the dev fee related functions aren't showing up in the typedocs. I think this will fix it.

Add swap with dev fee to typedocs

---

sdk/src/quotes/public/decrease-liquidity-quote.ts

- `decreaseLiquidityQuoteByLiquidity` does not have to be an async function

Remove async from decreaseLiquidityQuote

---

sdk/src/impl/position-impl.ts
sdk/src/impl/whirlpool-client-impl.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/instructions/composites/collect-all-txn.ts
sdk/src/quotes/swap/tick-array-sequence.ts
sdk/src/utils/builder/position-builder-util.ts
sdk/src/utils/public/tick-utils.ts
sdk/src/utils/whirlpool-ata-utils.ts
sdk/src/whirlpool-client.ts

- Add WhirlpoolData, TickArrayData to Position (client object) to allow for an easier time to generate quotes
- Change collect fee to user PositionData instead of client Position since it doesn't need that much info
- Add new TickUtil.getOffsetIndex to calculate array offset index for a position's tick
- The `client.getPositions` is used by Orca UI
- Confirmed that it successfully fetches all positions and have identical data to live (test case had 7 positions, SOL & nonSOL pairs)
- The UX performance is actually faster because the old version does not do batch RPC
https://app.asana.com/0/0/1203431351729803/f

Expose more data on PositionUtil for easier quote generation

---

sdk/src/impl/position-impl.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/instructions/composites/collect-all-txn.ts
sdk/src/utils/spl-token-utils.ts
sdk/src/utils/whirlpool-ata-utils.ts
sdk/src/whirlpool-client.ts

- Added a flag to getTokenMintsFromWhirlpools to reuse mint detection for different usecases
- Tested and confirmed that wSOL wrapping fits in the max filled close-position txbuilder
- Removed tokenaccount check for collectRewards
Next steps:
We are using existing tests to verify whirlpool.closePosition. However, the test coverage is not complete. We still need the following:
1. ClosePosition with decreaseL only
2. ClosePosition with collectFees only
3. ClosePosition with collectRewards only
4. ClosePosition with no collection/decreaseL, only close_position
5. Position.collectReward - verify the plumbing is correct with all param options turned on (payer, other wallet, SOL handling)
6. Position.collectFees - verify the plumbing is correct with all param options turned on (payer, other …

Proposal - Comments for closePosition patch

---

sdk/jest.config.js
sdk/src/quotes/swap/swap-quote-impl.ts
sdk/src/quotes/swap/tick-array-sequence.ts
sdk/src/utils/public/swap-utils.ts
sdk/tests/integration/open_position.test.ts
sdk/tests/integration/open_position_with_metadata.test.ts
sdk/tests/sdk/whirlpools/position-impl.test.ts
sdk/tests/sdk/whirlpools/swap/swap-traverse.test.ts
sdk/tests/sdk/whirlpools/utils/swap-utils.test.ts
sdk/tests/sdk/whirlpools/utils/tick-array-sequence.test.ts

Issue: https://app.asana.com/0/1202413563699470/1203471728007402/f
porting "shifted" in in_search_range of on-chain programs.
https://github.com/orca-so/whirlpools/blob/main/programs/whirlpool/src/state/tick.rs#L299
- getTickArrayPublicKeys: if the swap direction is B to A and tickCurrentIndex is greater than or equal to the last initializable tick in the TickArray, the TickArray adjacent to the swap direction is TickArray0
- TickArraySequence: Change the logic to determine whether TickArray0 contains tickCurrentIndex
- set jest timeout to 30 sec (default timeout (5 sec) is too short)
- add "integration" test to jest.config.js
- change "before" to "beforeAll"
In jest there is no before, use beforeAll for one-time setups
https://jestjs.io/docs/setup-teardown
- add refresh=true on …

fix: getTickArrayPublicKeys edge case

---

sdk/src/impl/position-impl.ts
sdk/src/impl/whirlpool-impl.ts
sdk/src/quotes/public/collect-rewards-quote.ts
sdk/tests/integration/collect_reward.test.ts
sdk/tests/integration/open_position.test.ts
sdk/tests/integration/open_position_with_metadata.test.ts
sdk/tests/sdk/whirlpools/position-impl#collectRewards.test.ts
sdk/tests/sdk/whirlpools/whirlpool-impl#closePosition.test.ts
sdk/tests/sdk/whirlpools/whirlpool-impl.test.ts

- Do not append updateFee ix if liquidity is zero in collectFee & collectReward util fn
- Fix collectRewardQuote use an estimated rewardGlobal accrued till the current timestamp
- Prior to this patch, collectRewardQuote is understating amount collected from call
- Fix unit-tests to strictly verify amount collected from collectFee, collectReward and closePosition
- Verified using refactored / new unit-tests that compares the collectRewardsQuote value to the actual collected amount . The quote is generated using the same timestamp as the one executed on-chain in the test case to ensure the clock values are the same.
- Verified that Position.collectReward & collectFees will not fail on-chain if position liquidity is zero & updateFeesAndRewards is enabled
- Ran all the other tests, all pass.

Fix understated collectRewardsQuote and unit-tests for new collect functions

---

programs/whirlpool/src/manager/swap_manager.rs
sdk/tests/integration/swap.test.ts

- Addresses edge case where swapping liquidity across an initialized tick boundary could cross the tick boundary but remain on the initialized tick.
- These edge cases could cause the fees and rewards in some pools to be calculated incorrectly due to actual liquidity diverging from calculated liquidity. As part of this fix, all pools were audited to ensure each pool contained appropriate liquidity and no user deposits were lost.
- This update was deployed to mainnet on [[Block #168,120,167](https://explorer.solana.com/block/168120167)](https://explorer.solana.com/block/168120167).

Handle liquidity swapping edge case across initialized tick boundary

---

sdk/package.json
sdk/tests/integration/open_position_with_metadata.test.ts
yarn.lock

- use common-sdk v0.1.10
- fix: open_position_with_metadata integration test (update URI of the metadata of position NFTs)
related: https://github.com/orca-so/whirlpools/pull/83
- ```anchor test``` passed

bump to v0.8.2

---

sdk/tests/utils/fixture.ts
sdk/tests/utils/swap-test-utils.ts
sdk/tests/utils/test-builders.ts

- tokenAIsNative was extended to reuseTokenA, but there was a bug that was fixed.
- Change the generation logic so that the mint specified in reuseTokenA is always tokenA (first mint). 
Removed cause of accidental SOL-SPL pool test failures.

fix: test cases (tokenAIsNative related)

---

sdk/src/prices/calculate-pool-prices.ts
sdk/src/prices/price-module.ts
sdk/tests/integration/get_pool_prices.test.ts

Reflect performance-enhancing changes that were necessary to integrate into the UI.
Eliminate PDA calculations by first calculating the most liquid pool for each pair with quoteToken, rather than checking for its existence in the poolMap while generating PDAs.
Only fetch TickArrays in the necessary direction, since swap is only attempted in the direction of the quoteToken with the higher priority.
Although the fetching of TickArray can be done in parallel, we want to minimize the number of account fetched because it takes time to decode and parse a 10KB account.

optimize price module perf

---

sdk/src/network/public/fetcher.ts
sdk/src/types/public/anchor-types.ts
sdk/tests/sdk/types/anchor-types.test.ts

Previously whirlpool account size was hardcoded to be an IDL index with the assumption that we would not add more account types. With `PositionBundle` added, the ordering of accounts on the IDL changed.
This patch fetches account sizes by the `AccountName` instead and adds a test to verify all `AccountName` enums have an IDL account entry.

Get anchor account sizes by name instead of IDL index

---

sdk/tests/sdk/types/anchor-types.test.ts

Fixing small issue in the test where `actualSize` variable wasn't being populated.

Fix usage of actual size variable in test used for logging

---

sdk/tests/utils/token.ts

If two pools are initialized in order to test two hop swaps it fails upon initializing the second pool using `initTestPool` because the token account for the reused token account A has already been created for pool one.
This pull requests reuses an already existing token account thereby enabling testing two pool swaps and initializing two pools in the same test that share the same tokenA. 
Context:
We are submoduling the whirlpools repo to test an integration, reusing provided test initialisers.

fix testing two hop swaps

---

sdk/src/instructions/composites/swap-with-route.ts

Since updatedQuote is not a deep copy, assigning directly to hopQuotes can cause assign to freezed object errors

Fix deep copy crash on quote adjustment

---

sdk/src/types/public/anchor-types.ts

- This IDL is needed for scripts that wants to read & decode Whirlpool transactions

Export Whirlpool IDL for external usage

---

sdk/src/impl/whirlpool-impl.ts
sdk/src/whirlpool-client.ts

Add an optional parameter to specify the positionMint instead of generating it internally. This allows the ability to assign an ephemeral keypair that can be saved for later execution in the case of a multi-sig wallet.

add optional position mint params

---

sdk/src/utils/position-util.ts

There is currently an edge case in the `increaseLiquidityQuoteByInputToken` function that could create a div-by-zero error. This specific case happens when (1) specifying tokenB input, and (2) the `tickLowerIndex` is equal to `tickCurrentIndex`.
Basically what happens in this case is that this quote is calculated as being in-range which then calls `getLiquidityFromTokenB` with  `sqrtPriceLowerX64` and `sqrtPriceX64` that are equal to each other.
https://github.com/orca-so/whirlpools/blob/61b262de70a68cc2169fcdd1916fc6f9c484b25c/sdk/src/quotes/public/increase-liquidity-quote.ts#L197
This then causes the denominator (diff between the two sqrtPrices) to be zero which then causes a div-by-zero a few lines later:
https://github.com/orca-so/whirlpools/blob/61b262de70a68cc2169fcdd1916fc6f9c484b25 …

Fix a div by zero bug in increaseLiquidityQuoteByInputToken calculations

---

sdk/package.json
sdk/src/impl/whirlpool-impl.ts
sdk/tests/sdk/whirlpools/whirlpool-impl#closePosition.test.ts
yarn.lock

Right now the closePosition transaction builder potentially creates two transactions if ATAs need to be created. Tx one contains the CreateATA instructions and tx two contains the instructions related to closing the position.
This PR changes this logic and puts all instructions for closePosition in a single transaction (like we were already doing for collectFees and collectRewards).
@yugure-orca opted for not changing the instruction to CreateATAIdempotent because the logic is fetching the accounts either way. If we want that improvement there is a bigger change needed in `common-sdk`.

Reduced close position transaction builder to a single transaction

---

sdk/package.json
sdk/src/instructions/composites/swap-with-route.ts

During a two-hop swap an intermediate token account needs to be created if it does not exist already. If this account did not exist before the amount in this token account will be 0 after the swap. The user did however pay rent for this account in the transaction and needs to manually reclaim this rent by closing the account.
This PR closes any intermediate token accounts that are created during a two-hop swap. Token accounts that were already created before a two-hop swap will be left intact (so they are only closed if they are created in the same transaction). This way the user never has to pay rent to create an intermediate token account during a two-hop swap.
Verified all tests still pass

Close intermediate token accounts of 2-hop swap

---

sdk/package.json
yarn.lock

Bump common-sdk to pick up priority fee changes in transaction builder.
0.5.2 needs to be published after https://github.com/orca-so/orca-sdks/pull/73 is merged.

Bump common-sdk to 0.5.2

---

sdk/package.json
sdk/src/instructions/composites/swap-async.ts
sdk/tests/sdk/whirlpools/whirlpool-impl.test.ts

Asana: https://app.asana.com/0/1202413563699470/1206926743112719/f
Resolve double ATA creation issue.
It happens because some users will build and send multiple transactions simultaneously.
- ``anchor test`` passed
- added new 1 test case to ensure Idempotent is used

use idempotent on whirlpool.swap (swapAsync)

---

programs/whirlpool/src/util/v2/token.rs
sdk/src/utils/public/pool-utils.ts
sdk/tests/integration/v2/initialize_pool_v2.test.ts
sdk/tests/integration/v2/token-extensions/non-confidential-transfer+transfer-fee.test.ts
sdk/tests/utils/v2/confidential-transfer.ts
sdk/tests/utils/v2/token-2022.ts

When both `TransferFeeConfig` and `ConfidentialTransferMint` are initialized, `ConfidentialTransferFeeConfig` must be initialized.
https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/extension/mod.rs#L1292
So we need to support `ConfidentialTransferFeeConfig` extension.
Whirlpool uses only non-confidential transfers, so this extension is not used in Whirlpool's operation, but must be allowed to be set to mint.

add ConfidentialTransferFeeConfig extension support

---

sdk/src/quotes/public/increase-liquidity-quote.ts

first and second JS doc params were flipped

Fix JS doc ordering for increaseLiquidityQuoteByInputToken

---

programs/whirlpool/src/errors.rs
programs/whirlpool/src/math/tick_math.rs
programs/whirlpool/src/state/position.rs
programs/whirlpool/src/state/tick.rs
sdk/src/types/public/constants.ts
sdk/src/utils/public/tick-utils.ts
sdk/tests/integration/open_bundled_position.test.ts
sdk/tests/integration/open_position.test.ts
sdk/tests/integration/open_position_with_metadata.test.ts
sdk/tests/sdk/whirlpools/utils/tick-utils.test.ts
sdk/tests/utils/index.ts

* Added check to disallow non-full-range positions on pools with tick spacing >= 2^15
* Added tests for `open_position`, `open_position_with_metadata` and `open_bundled_position`

Disallow non-full-range positions on pools with tick spacing >= 2^15

---

sdk/src/instructions/composites/swap-async.ts
sdk/src/instructions/composites/swap-with-route.ts
sdk/src/instructions/swap-ix.ts
sdk/src/instructions/two-hop-swap-ix.ts
sdk/src/instructions/v2/swap-ix.ts
sdk/src/instructions/v2/two-hop-swap-ix.ts
sdk/src/prices/calculate-pool-prices.ts
sdk/src/quotes/public/swap-quote.ts
sdk/src/quotes/public/two-hop-swap-quote.ts
sdk/src/quotes/swap/tick-array-sequence.ts
sdk/src/types/public/client-types.ts
sdk/src/utils/public/swap-utils.ts
sdk/src/utils/swap-utils.ts
sdk/tests/sdk/whirlpools/swap/swap-array.test.ts
sdk/tests/sdk/whirlpools/swap/swap-with-fallback.test.ts
sdk/tests/sdk/whirlpools/swap/v2/swap-array.test.ts
sdk/tests/sdk/whirlpools/utils/swap-utils.test.ts
sdk/tests/sdk/whirlpools/utils/tick-array-sequence.test.ts
sdk/tests/utils/testDataTypes.ts

This PR introduces the benefits provided by SparseSwap into SDK.
The swapQuoteX function gets the estimate without any concern for the existence of uninitialized TickArrays.
Whirlpool.swap and the swapAsync behind it no longer pre-verify whether a TickArray is initialized or not.
To enjoy the benefit of not having to worry about uninitialized TickArrays by default, the SDK interpolate uninitialized TickArrays with zeroed data in swapQuoteWithParams function.
As a result, functions that use swapQuoteWithParams, such as sqapQuoteByInputToken, also benefit.
- `swapQuoteByInputToken` --> `swapQuoteWithParams`
- `swapQuoteByOutputToken` --> `swapQuoteWithParams`
- `swapQuoteWithParams` (direct use)
On the other hand, the behavior of supplemental tick arrays and preliminary additions to …

SparseSwap (SDK)

---

Cargo.lock
programs/whirlpool/Cargo.toml
sdk/tests/integration/open_bundled_position.test.ts
yarn.lock

`spl-transfer-hook-interface` 0.5.1 have been yanked.
https://crates.io/crates/spl-transfer-hook-interface/versions
Whirlpool program can be built because its version is locked by Cargo.lock.
But some partners could not use the prograam as one of dependencies.
But 0.6.x and 0.7.x only supports solana 1.18, and we are on 1.17.
So I changed version to 0.5.0 because there is no difference. (0.5.1 is created as version bump)
https://github.com/solana-labs/solana-program-library/commit/950efde273d19b23343636df8acbde82a6883e04
`0.5.1` have been yanked but it is not due to security issue. Just Solana 2.0.0 version issue.
https://github.com/solana-labs/solana-program-library/issues/6897#issuecomment-2186394953
fix test cases for Full Range Only pool: https://github.com/orca-so/whirlpools/pull/161 …

Fix yanked dependency and failed tests

---

legacy-sdk/whirlpool/package.json
legacy-sdk/whirlpool/src/impl/whirlpool-client-impl.ts
legacy-sdk/whirlpool/src/types/public/constants.ts
legacy-sdk/whirlpool/src/whirlpool-client.ts
legacy-sdk/whirlpool/tests/sdk/whirlpools/whirlpool-client-impl.test.ts

Add a helper function for creating splash pools. Some people have complained that it is not clear how to create a splash pool from the UI. This PR is a short term solution for this. In v2 sdk we should think of a better way to set this up and make the devex better

Create a helper function for creating splash pools

---

.github/workflows/checks.yml

This did not behave as intended so removing it again. Basically I thought this would cancel running jobs on a per-branch basis meaning that if you push a new commit to a branch it cancels all in-progress jobs for that branch. This however works on a global-basis meaning that one PR can cancel the workflow run of another PR. I have changed the key to something unique per branch meaning that one branch can only ever cancel in-progress workflows for that specific branch.
Reference: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs

Fix concurrency group for the checks gh actions workflow

---

.github/dependabot.yml

This should create a single PR for dependencies of the program. This will still create separate dependencies for security-updates. If a crate is marked as vulnerable and an update is available this will still be in a separate PR.

Dependabot group program dependency updates

---

legacy-sdk/whirlpool/tests/integration/multi-ix/splash_pool.test.ts
legacy-sdk/whirlpool/tests/integration/swap.test.ts
legacy-sdk/whirlpool/tests/integration/two_hop_swap.test.ts
legacy-sdk/whirlpool/tests/integration/v2/collect_fees_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/swap_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/two_hop_swap_v2.test.ts
legacy-sdk/whirlpool/tests/utils/v2/aquarium-v2.ts
programs/whirlpool/src/errors.rs
programs/whirlpool/src/instructions/two_hop_swap.rs
programs/whirlpool/src/manager/swap_manager.rs
programs/whirlpool/src/math/swap_math.rs

Trades may complete with partial fill when sqrt_price_limit is reached in both ExactIn and ExactOut.
In ExactIn, the amount of output is verified by other_amount_threshold, so even if a partial fill occurs, the transaction will fail unless the trader obtains the desired output for the input.
In ExactOut, on the other hand, other_amount_threshold defines an upper limit on the amount of input, so that a transaction will not fail when a part of input amount is used. However, this may result in an unfavorable rate if the specified amount of output is not obtained due to partial fill.
For traders who wish to explicitly reject the occurrence of Partial fill in ExactOut, the program will accept an input of sqrt_price_limit = 0. If sqrt_price_limit = 0, then if a Partial fill occurs in ExactOut, …

Reject partial fill in ExactOut if sqrt_price_limit = 0

---

.github/dependabot.yml
.github/workflows/publish.yml
README.md
docs/legacy/typedoc.json
docs/ts/typedoc.json
legacy-sdk/whirlpool/package.json
package.json
programs/whirlpool/Cargo.toml
rust-sdk/client/Cargo.toml
rust-sdk/client/README.md
rust-sdk/whirlpool/Cargo.toml
rust-sdk/whirlpool/README.md
ts-sdk/client/README.md
ts-sdk/client/package.json
ts-sdk/whirlpool/README.md
ts-sdk/whirlpool/package.json

This would only publish `client` packages on tag. The other packages are still WIP and will not be published yet

Add github actions publish script for npm and crates

---

programs/whirlpool/src/util/v2/token.rs

`transfer_hook_accounts` are cloned and referenced immediately which wastes CU and memory unnecessarily:
https://github.com/orca-so/whirlpools/blob/8c596979c40d0fc4658a819b0fbdbe438a73fcac/programs/whirlpool/src/util/v2/token.rs#L83
https://github.com/orca-so/whirlpools/blob/8c596979c40d0fc4658a819b0fbdbe438a73fcac/programs/whirlpool/src/util/v2/token.rs#L162
Remove unnecessary cloning of transfer hook accounts and reference them instead.

Remove unnecessary cloning of transfer hook accounts

---

.github/actions/version/action.yml
.github/workflows/dependabot.yml
.github/workflows/publish.yml

Tested locally using `act`. 
This setup *should* work for the `client` packages since they have no dependencies on other packages in this monorepo. 
For the other packages we would also need to update the local deps' version num (wrote a little bit but still commented out in the actions file). We can fix this later when we deploy those packages.

More sophisticated version setting for publish gh action

---

.github/workflows/publish.yml

* Github runner comes preconfigured with ghpr as node registry instead of npmjs (worked locally but not on gh runner)
* Action is calling for `CARGO_REGISTRY_TOKEN` as the env variable instead of `CRATES_IO_API_TOKEN`

Fix two bugs in publish github actions script

---

.github/workflows/publish.yml

Because it is running in a container, `env` doesn't work since that sets environment variables in the host and not in the build container

Fix a bug with publish gh actions env variables

---

.github/workflows/publish.yml

Almost there 😁 
**Issue**: `NODE_AUTH_TOKEN` only works with the [setup-node](https://github.com/actions/setup-node) action which we cannot use since we are running in a build container and not on the host itself
**Solution**: add auth token to .npmrc manually

Fix an issue with npm deploy token in gh actions

---

.github/workflows/publish.yml

Workflow itself works fine and release is created. Only the idl artifact is not attached to the release correctly: 
```
Warning: Artifact is a directory:idl/. Directories can not be uploaded to a release.
```
Change the release title to `SDK - vX.X.X` so that we can still make distinction between SDK and program releases

Fix a small bug with publish script not adding idl to gh release

---

legacy-sdk/whirlpool/package.json
legacy-sdk/whirlpool/src/instructions/composites/swap-async.ts
legacy-sdk/whirlpool/src/quotes/public/swap-quote.ts
legacy-sdk/whirlpool/src/utils/public/pool-utils.ts
legacy-sdk/whirlpool/tests/sdk/whirlpools/swap/swap-edge-case.test.ts

This PR will fix the following 3 issues.
Current SDK implementation always wrap `amount` of SOL if input token is SOL.
But in ExactOut case, `amount` is output amount and may be not SOL.
In ExactOut case, we need to use `otherAmountThreshold` as input amount.
swapQuotesByInputToken receives `opts`.
But even when we use `IGNORE_CACHE`, it will try to use `whirlpool.getData()`.
It is cached value, so user cannot get the latest quote. (Only TickArray state will be refreshed)
estimateLiquidityFromTokenAmounts uses currTick so its result is not accurate.
To avoid breaking change, I introduced `estimateMaxLiquidityFromTokenAmounts`.
It uses `sqrtPriceX64`.
Also `estimateLiquidityFromTokenAmounts` have been deprecated.

Fix: ExactOut + SOL input WSOL handling and missing refresh

---

legacy-sdk/whirlpool/src/utils/public/pool-utils.ts
legacy-sdk/whirlpool/tests/integration/v2/initialize_pool_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/initialize_reward_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/token-extensions/interest-bearing.test.ts
legacy-sdk/whirlpool/tests/utils/v2/init-utils-v2.ts
legacy-sdk/whirlpool/tests/utils/v2/token-2022.ts
programs/whirlpool/src/util/v2/token.rs

https://linear.app/orca-so/issue/INF-149/[amm]-interestbearing-support
- The program handles u64 amount (raw amount) only. (not handle UI Amount)
- TokenBadge is not required.
~~The handling of InterestBearing is being discussed so as not to create confusion throughout the Solana ecosystem.
Supporting it should wait for now.~~
There is no problem to enable it on the contract side, so we'll merge the PR.
We need to tackling to the difficulty in handling InterestBearing on the UI side. 😂

InterestBearing support

---

rust-sdk/client/Cargo.lock
rust-sdk/whirlpool/Cargo.lock
ts-sdk/whirlpool/src/config.ts
ts-sdk/whirlpool/src/createPool.ts
ts-sdk/whirlpool/src/decreaseLiquidity.ts
ts-sdk/whirlpool/src/harvest.ts
ts-sdk/whirlpool/src/increaseLiquidity.ts
ts-sdk/whirlpool/src/pool.ts
ts-sdk/whirlpool/src/position.ts
ts-sdk/whirlpool/src/swap.ts
ts-sdk/whirlpool/src/token.ts

Typedocs for TS SDK
- Use `export` keyword to create clickable types in typedocs
- Add documentation to types and exported functions
- Add examples usage to documentation

Typedocs for TS SDK

---

.github/actions/version/action.yml
.github/workflows/publish.yml

Only the version field of the package itself was being set in the previous version of the script. This was fine for the `client` packages since they do not depend on any local dependencies. Now that we would like to publish `core` and `whirlpool` for TS we need a small change.
New version of this script changes both the version of the package itself, and the version of local dependencies that the package has.

Properly set version numbers in publish script

---

ts-sdk/core/package.json

Package on npm is currently empty so I guess wildcard does not work

Fix ts core lib included files

---

ts-sdk/core/package.json

Because of the `.gitignore` files that wasm-pack creates, npm ignores all the files in that subfolder, meaning the actual wasm bundle doesn't get included in the npm package.
with this change:
```
npm notice total files: 10
```
without this change:
```
npm notice total files: 2
```

Fix a bug in publishing ts-sdk/core

---

docs/whirlpool/docusaurus.config.js

Add Whirlpools SDK dropdown to navbar
- Added a "Whirlpools SDK Reference" dropdown to the navbar.
- The dropdown includes links to "TS SDK Reference" and "Rust SDK Reference".
- This change groups the SDK references under a single menu item for better organization and easier navigation.

Add Whirlpools SDK dropdown to navbar

---

docs/rust/Cargo.toml

Currently the rustdoc builds with the `wasm` feature enabled. This adds certain fields that are only used in `wasm` to the docs. These features are not available otherwise so shouldn't show up in the docs.
Example is the wasm_expose const functions that the macro adds

Build rustdoc without 'wasm' feature

---

ts-sdk/whirlpool/src/position.ts

`getTokenAccountsByOwner` does not work with `base58` encoding. I switched it over to `base64` encoding.

Fix a bug fetching positions for owner

---

rust-sdk/client/codama.js
rust-sdk/client/package.json
ts-sdk/client/codama.js
ts-sdk/client/package.json
ts-sdk/core/tests/types.test.ts
yarn.lock

Kinobi has been renamed to Codama: https://github.com/codama-idl/codama/pull/234. This PR updates to the new `codama` packages

Use Codama instead of Kinobi

---

docs/whirlpool/docs/03-Whirlpools SDK/02-Whirlpool Management/02-Fetch Pools.md
ts-sdk/whirlpool/src/pool.ts

During the ts-sdk PR I remember there were a couple of comments about this but turns out I never actually ended up changing it. Theoretically this is now a breaking change since the ts-sdk has been deployed but I think this is semi-fine given that it has only been deployed for a week.
The issue with the `fetchWhirlpools` name is that it conflicts with `fetchWhirlpool` and `fetchAllWhirlpools` from whirlpools-client.

Rename `fetchWhirlpools` to `fetchWhirlpoolsByTokenPair`

---

ts-sdk/whirlpool/src/createPool.ts
ts-sdk/whirlpool/src/pool.ts
ts-sdk/whirlpool/src/token.ts
ts-sdk/whirlpool/tests/token.test.ts

Issue: ts-code was comparing `utf8(address_in_base58)` while it should have been comparing `address_in_bytes`. This is because `Buffer.from(Address)` does not return the address bytes but instead takes the string (which Address basically is) and convert that to utf8 bytes.

Fix a bug ordering tokens

---

rust-sdk/client/Cargo.toml
rust-sdk/core/Cargo.toml
rust-sdk/integration/Cargo.toml
rust-sdk/integration/index.test.ts
rust-sdk/integration/package.json
rust-sdk/integration/src/main.rs
rust-sdk/integration/tsconfig.json
yarn.lock

Added an integration test that tests various versions of anchor and solana

Made dependencies of orca_whirlpools_client less strict

---

rust-sdk/core/src/constants/error.rs
rust-sdk/core/src/math/tick.rs

Couple issues
1) No tests for this function
2) Think it handled negative tick indexes correctly (negative number minus a larger negative number = positive) but made it more explicit
3) Undefined behaviour if a tick index outside of a tick array was specified

Improve calculating index in tick array

---

docs/whirlpool/docs/03-Whirlpools SDKs/03-Whirlpools/03-Whirlpool Management/01-Create Pool.md
legacy-sdk/scripts/genExpBitConstants.ts
legacy-sdk/scripts/whirlpoolNft.json
legacy-sdk/whirlpool/src/network/public/fetcher/fetcher-impl.ts
legacy-sdk/whirlpool/tests/integration/open_position_with_metadata.test.ts
legacy-sdk/whirlpool/tests/utils/v2/token-2022.ts
programs/whirlpool/src/instructions/open_position_with_metadata.rs

**Title**
Fix broken links
**Details**
- Searched for instances of 'http' to identify outdated or broken links.
- Updated links to use correct URLs.

Fix broken links

---

ts-sdk/client/package.json
ts-sdk/whirlpool/package.json
ts-sdk/whirlpool/src/createPool.ts
ts-sdk/whirlpool/src/decreaseLiquidity.ts
ts-sdk/whirlpool/src/increaseLiquidity.ts
ts-sdk/whirlpool/src/swap.ts
yarn.lock

Web3.js v2 is now recommended for general use. This PR drops the rc version and updates to v2

Use web3.js v2.0.0

---

ts-sdk/whirlpool/src/position.ts

Internally we used the property `owner` to store the `tokenProgram` in a `Token` object. This might create confusion since `Token` already has `owner` which is the owner of the token account. 
Externally this doesn't change anything since the `Token` object is not returned by the function.

Small improvement to fetchPositionsForOwner

---

legacy-sdk/cli/README.md
legacy-sdk/cli/src/commands/set_reward_authority.ts
legacy-sdk/cli/src/commands/set_reward_emissions_super_authority.ts
legacy-sdk/cli/src/utils/transaction_sender.ts

Added the following cli commands:
- setRewardEmissionsSuperAuthority
- setRewardAuthority
Those commands have been used to adjust authorities on the config and pools in Eclipse.
(It worked as expected)

Add set reward authority cli commands

---

ts-sdk/client/src/gpa/whirlpool.ts

**Title**
Add Example Usage to Fetch All Whirlpool Accounts with Specified Filters
**Details**
Fetching all pools is a much requested feature by developers. Adding an example of how this can be done using our SDK makes it easier for DAs to point developers in the right direction.

Add Example Usage to Fetch All Whirlpool Accounts with Specified Filters

---

rust-sdk/core/src/math/tick_array.rs

Hi Orca team,
I found a potential overflow when I was trying to calculate quote for SOL -> USDC using `orca_whirlpools_core` in debug mode.
More specifically, `next_start_tick_index` might be `i32::MAX` and `current_start_tick_index` might be negative value like `-13728`, Rust would panic with error: `attempt to subtract with overflow`
This fix uses  short-circuit evaluation to work around this check, maybe a more explicit fix is to convert `next_start_tick_index` to `i64`?

Fix potential overflow issue

---

.github/actions/version/action.yml

Right now the following gets replaced incorrectly:
```
orca_whirlpools_core = { path = "../core", features = ["floats"] }
```
Before this change it would turn into
```
orca_whirlpools_core = { version = "x.x.x"] }
```
After this change it turns into
```
orca_whirlpools_core = { version = "x.x.x", features = ["floats"] }
```

Fix a bug in version setting action

---

examples/rust-sdk/whirlpool_repositioning_bot/src/utils.rs

**TITLE**
Replace deprecated `status` check with `err` validation
**DESCRIPTION**
This PR updates the signature status check logic in the example Rust project to align with the latest [Solana RPC documentation](https://solana.com/docs/rpc/http/getsignaturestatuses).
The status field in the response of `getSignatureStatuses` has been deprecated. The logic has been updated to validate the `err` field instead, which determines whether a transaction was successful or failed.

Update `send_transaction()` in example Rust project

---

legacy-sdk/cli/src/commands/close_position.ts
legacy-sdk/whirlpool/src/impl/whirlpool-impl.ts

Description:
This PR fixes a constraint error that occurs when calling closePosition on a position that has uninitialized rewards. The error message indicates that the reward_owner_account.mint does not match the expected mint address stored in whirlpool.reward_infos[reward_index].mint. This issue arises because closePosition attempts to collect rewards for all possible reward indexes, including those that are not initialized.
**Problem Statement:**
When attempting to close a position using closePosition, a constraint error occurs if the whirlpool has uninitialized rewards. The error is due to the program trying to collect rewards for uninitialized reward indexes, resulting in mismatched mint addresses.
**Solution:**
Modify the getClosePositionIx method in whirlpool-impl.ts to skip any …

Users unable to close positions on ME/SOL pool without harvesting first

---

docs/whirlpool/docs/03-Whirlpools SDKs/01-Whirlpools/02-Environment Setup.mdx
docs/whirlpool/docs/03-Whirlpools SDKs/01-Whirlpools/05-Trade.mdx
docs/whirlpool/docs/03-Whirlpools SDKs/01-Whirlpools/06-Send Transaction.mdx
ts-sdk/whirlpool/README.md

**Title**
Add Docs for Sending and Landing Transactions with Whirlpools SDK in Rust and TS
**Details**
This PR adds documentation on sending and landing transactions using the Whirlpools SDK and Solana SDK in both Rust and TypeScript.
- Includes Rust and TS code snippets for generating instructions, creating transaction messages, estimating compute units and fees, and submitting transactions with client side retry.
- Added explanations on blockhashes, transaction lifetimes, compute unit limits, prioritization fees, and retry logic.
- Added a section geared to web app developers interacting with browser wallets
- Added a section with additional recommendations for improving transaction landing.

Add `send transaction` to TS and Rust code examples

---

legacy-sdk/whirlpool/package.json
legacy-sdk/whirlpool/src/impl/whirlpool-impl.ts

#588 didn't actually fix the issue fully yet. My guess is that the issue stopped happening because rewards expired.
There was one small thing still wrong with the rewardIndex as it takes the index of the reward after filtering but is should take the index before filtering.

Fix a bug in legacy-sdk with closing position

---

rust-sdk/core/src/quote/fees.rs
rust-sdk/core/src/quote/rewards.rs

Right now the new core sdk mishandles the cyclic aspect of fee and rewards quotes. Currently it for the checkpoint calculation, it wraps around u256 while it should be wrapping around u128.
I've fixed the issue and added a test case

Fix a bug with the cyclic fee/rewards quote calculation

---

docs/whirlpool/docs/03-Whirlpools SDKs/01-Whirlpools/04-Position Management/02-Fetch Positions.mdx

The get_positions_for_owner is not available in orca_whirlpools and fetch_positions_for_owner is working.

docs: rename function get_positions_for_owner to fetch_positions_for_owner

---

Cargo.toml
ts-sdk/whirlpool/tests/closePosition.test.ts
ts-sdk/whirlpool/tests/harvest.test.ts
ts-sdk/whirlpool/tests/utils/program.ts

- Add tests for close position
- Add tests for decrease liquidity
- Add tests for harvest position

Add tests for close position, decrease liquidity, and harvest position

---

scripts/deploy-cargo
scripts/deploy-docs
scripts/deploy-npm

Fix publishing docs to gh pages

---

.github/actions/push/action.yml
.github/actions/ssh/action.yml

Fix github pages publish

---

.changeset/true-pens-drum.md
legacy-sdk/whirlpool/tests/integration/decrease_liquidity.test.ts
legacy-sdk/whirlpool/tests/integration/increase_liquidity.test.ts
legacy-sdk/whirlpool/tests/integration/initialize_pool.test.ts
legacy-sdk/whirlpool/tests/integration/swap.test.ts
legacy-sdk/whirlpool/tests/integration/two_hop_swap.test.ts
legacy-sdk/whirlpool/tests/integration/v2/decrease_liquidity_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/increase_liquidity_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/initialize_pool_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/swap_v2.test.ts
legacy-sdk/whirlpool/tests/integration/v2/token-extensions/transfer-fee.test.ts
legacy-sdk/whirlpool/tests/integration/v2/two_hop_swap_v2.test.ts
programs/whirlpool/src/events.rs
programs/whirlpool/src/instructions/decrease_liquidity.rs
programs/whirlpool/src/instructions/increase_liquidity.rs
programs/whirlpool/src/instructions/initialize_pool.rs
programs/whirlpool/src/instructions/swap.rs
programs/whirlpool/src/instructions/two_hop_swap.rs
programs/whirlpool/src/instructions/v2/decrease_liquidity.rs
programs/whirlpool/src/instructions/v2/increase_liquidity.rs
programs/whirlpool/src/instructions/v2/initialize_pool.rs
programs/whirlpool/src/instructions/v2/swap.rs
programs/whirlpool/src/instructions/v2/two_hop_swap.rs
programs/whirlpool/src/lib.rs
programs/whirlpool/src/manager/swap_manager.rs

For event emission release
note: PR59

Event emission

---

.gitignore

Added .idea directory to .gitignore to prevent JetBrains IDE configuration files (e.g., workspace settings, run configurations) from being committed. This ensures a cleaner repository and avoids conflicts between developers using different IDE settings.

chore(gitignore): add .idea to ignore JetBrains IDE files

---

.changeset/fast-hotels-flow.md
legacy-sdk/whirlpool/src/impl/whirlpool-client-impl.ts
legacy-sdk/whirlpool/tests/sdk/whirlpools/whirlpool-client-impl.test.ts

`initialize_pool` accepts `initial_sqrt_price` and it is not limited to "initializable tick".
`createPool` function restrict initial tick to be initializable (multiple of tick spacing), but this restriction is not needed.
https://github.com/orca-so/whirlpools/blob/main/programs/whirlpool/src/instructions/initialize_pool.rs#L55
Note: `createSplashPool` function doesn't have this restriction.

Remove isTickInitializable check on createPool

---

.changeset/common-apples-sin.md
legacy-sdk/whirlpool/src/instructions/index.ts
legacy-sdk/whirlpool/src/instructions/transfer-locked-position.ts
legacy-sdk/whirlpool/src/ix.ts
legacy-sdk/whirlpool/tests/integration/lock_position.test.ts
legacy-sdk/whirlpool/tests/integration/transfer_locked_position.test.ts
programs/whirlpool/src/instructions/lock_position.rs
programs/whirlpool/src/instructions/mod.rs
programs/whirlpool/src/instructions/transfer_locked_position.rs
programs/whirlpool/src/lib.rs
programs/whirlpool/src/state/lock_config.rs
programs/whirlpool/src/util/shared.rs
programs/whirlpool/src/util/token_2022.rs

The initial LL implementation doesn't allow locking concentrated positions. (non FullRange positions)
This was not technical limitation.
This restriction was introduced to simplify the calculation of the proportion of locked liquidity.
We will relax the restriction in the contract.
Note: PR79 on dev repo
- no tweak
- no conflict
- no error code conflict

Allow locking concentrated positions

---

.changeset/chatty-cooks-push.md
docs/rust/Cargo.lock
rust-sdk/core/src/quote/liquidity.rs
rust-sdk/core/src/types/liquidity.rs
ts-sdk/whirlpool/src/index.ts

This PR exposes useful utility functions in both Rust and TypeScript SDKs:
- Exported `try_get_token_estimates_from_liquidity`. This is more straightforward then pointing users to use 'decreaseLiquidityQuote` functions to estimate their token balances.
- Add new interface `PositionTokenAmounts`
- Add tests
- Exports the `orderMints` utility function from the TypeScript SDK, similar to how the Legacy SDK export `PoolUtil.ordermints`

Expose useful utility functions in Rust and TypeScript SDKs

---

.changeset/dry-games-walk.md
.changeset/tall-views-visit.md
docs/rust/Cargo.lock
docs/whirlpool/docs/03-SDKs/03-Whirlpool Management/01-Create Pool.mdx
docs/whirlpool/docs/03-SDKs/04-Position Management/01-Open Position.mdx
docs/whirlpool/docs/03-SDKs/04-Position Management/02-Adjust Liquidity.mdx
docs/whirlpool/docs/03-SDKs/04-Position Management/03-Harvest.mdx
docs/whirlpool/docs/03-SDKs/04-Position Management/04-Close Position.mdx
docs/whirlpool/docs/03-SDKs/05-Trade.mdx
docs/whirlpool/docs/03-SDKs/06-Send Transaction.mdx
rust-sdk/tx-sender/src/compute_budget.rs
rust-sdk/tx-sender/src/lib.rs

The tx-sender SDK encountered "Transaction failed to sanitize accounts offsets correctly" errors in certain multi-signer scenarios. We identified that the `estimate_compute_units` function was simulating transactions with a fixed signature count that didn't match the actual number of signers used in the final transaction, causing a mismatch between simulation and execution.
- Added signers parameter to `estimate_compute_units` function to ensure consistent signature counts
- Updated transaction simulation to use `vec![Signature::default(); signers.len()]` for creating properly sized signature arrays
- removed `payer` from `build_transaction` and kept `signers`, bringing it in line with `build_and_send_transaction`.
- Updated Rust docs with example handling of `additional_signers`.
- Fixed …

Fix "Transaction failed to sanitize accounts offsets" by matching signature count in simulations

---

.changeset/silent-flowers-thank.md
Cargo.lock
docs/rust/Cargo.lock
rust-sdk/core/src/math/tick_array.rs
rust-sdk/core/src/quote/rewards.rs
rust-sdk/tx-sender/Cargo.lock
ts-sdk/core/tests/smoke.test.ts

This PR aligns the calculation for reward collection with that of the on-chain program and the Legacy SDK.
**Before**:
- `liquidity` × `reward_growth` multiplication in `U256`
- Cast result to `U64`
This led to a bug where the casting would throw an overflow error.
**Now**:
- `liquidity` × `reward_growth` multiplication in `U128`
- Bit shift right by 64
- Returns 0 if overflow (matching on-chain behavior)
- Cast to `U64`
**Testing**:
- Expected values in tests are verified against the `collectRewardQuote` function of the Legacy SDK
- Added test case to verify overflow handling behavior

Align Rust SDK `collect_reward_quote` calculation with on-chain program

---

.changeset/pretty-crabs-smoke.md
rust-sdk/core/Cargo.toml
rust-sdk/core/src/math/mod.rs
rust-sdk/core/src/quote/mod.rs
rust-sdk/core/src/types/mod.rs

This feature flag allows not including the swap-quote functions. These functions throw stack-overflow errors when building on-chain. Excluding them by disabling the feature allows callers to remove these errors:
```
Error: Function _ZN4core5slice4sort25insertion_sort_shift_left17hbe22a8e5677a339dE Stack offset of 10568 exceeded max offset of 4096 by 6472 bytes, please minimize large stack variables. Estimated function frame size: 10592 bytes. Exceeding the maximum stack offset may cause undefined behavior during execution.
Error: Function _ZN20orca_whirlpools_core4math10tick_array26TickArraySequence$LT$_$GT$3new17h1e2b4d7697623b0bE Stack offset of 63296 exceeded max offset of 4096 by 59200 bytes, please minimize large stack variables. Estimated function frame size: 63408 bytes. Exceeding …
```

Add swap feature flag to core sdk

---

.changeset/true-items-cross.md
programs/whirlpool/src/instructions/adaptive_fee/initialize_pool_with_adaptive_fee.rs
programs/whirlpool/src/instructions/v2/swap.rs

stack usage on initializePoolWithAdaptiveFee: 4040 bytes -> 3672 bytes
4040 is less than 4KB, but `access violation` error has been detected in mainnet.
(but not detected on solana-test-validator)
rsp operation check (this fix is included)
[Stack size est - try_accounts check.pdf](https://github.com/user-attachments/files/20162591/Stack.size.est.-.try_accounts.check.pdf)

Reduce stack size usage on initializePoolWithAdaptiveFee

---

.changeset/ready-ads-sort.md
rust-sdk/tx-sender/Cargo.lock
rust-sdk/tx-sender/Cargo.toml
rust-sdk/tx-sender/src/compute_budget.rs
rust-sdk/tx-sender/src/lib.rs

- **Problem**: If compute budget instructions are not provided during simulation, the max compute allowed is 400k. This will cause any simulation with compute unit intensive instructions to fail, which means that calls to `build_transaction` and `build_transaction_with_config` will fail.
- **Solution**: Parse provided instructions and add a compute budget instruction with max units if none exist.
- I ran into borsh versions issues in consuming packages due to the range of allowed solana related crate versions (sample errors below). After like ~1 hour of continuously failing, I pivoted and tried a different approach. The implementation is less maintainable than using `ComputeBudgetInstruction` and borsh directly, but I thought it might be an acceptable trade-off since the logic is …

add max compute unit limit to simulation instructions if none are provided

---

rust-sdk/client/src/core_types/tick_array.rs

The `From<TickArray>` for `TickArrayFacade` implementation had a circular reference causing infinite recursion and stack overflow. Specifically, the implementation called `val.into()`, which is shorthand for `From::from(val)` and looks for a `From<TickArray>` implementation for `TickArrayFacade`, resulting in recursively calling itself. This was confirmed with a test that demonstrated the issue by attempting to convert a minimal `TickArray` to `TickArrayFacade`.
- Replace recursive `val.into()` with proper match statement to delegate to specific variant implementations
- Add tests to verify both fixed and dynamic tick array conversions work correctly

Fix stack overflow in TickArray to TickArrayFacade conversion

---

.github/actions/anchor/action.yml

Now devnet is halted (planned shutdown)
https://github.com/anza-xyz/agave/wiki/2025-07-03-Devnet-rollback-and-restart
The current github action contains `solana airdrop 1` (devnet) as quick check for Solana CLI installation.
But now devnet doesn't produce new block, so transaction will not land and  will not expire forever...
To unblock Publish action, I'd like to remove this check for now.

Remove solana airdrop command (devnet is halted)

---

.changeset/witty-results-smell.md
docs/whirlpool/docs/05-More Resources/06-Whirlpool Replayer.mdx

**Updating 06-Whirlpool Replayer.mdx**
fixing quick typo :) caught while reading docs

Fix Typo - 06-Whirlpool Replayer.mdx

---

.changeset/icy-aliens-enjoy.md
rust-sdk/whirlpool/src/token.rs

- `prepare_token_accounts_instructions` generated nested ATA init instruction.
- Fixed wrong args on `create_associated_token_account`
- Fixed test cases
https://docs.rs/spl-associated-token-account/3.0.4/spl_associated_token_account/instruction/fn.create_associated_token_account.html

Fix: Wrong ATA init instruction generation

---

README.md
scripts/setup.sh

Added a setup script to streamline development environment setup:
**New Setup Script (`scripts/setup.sh`):**
- One-stop installation of all required dependencies (Node.js, Rust, Solana CLI, Anchor)
- Supports both Linux and macOS environments
- Installs specific versions required by the project (clearly defined at the top)
- Designed for fresh environments (cloud VMs, containers, new machines)
**Updated Documentation:**
- Update "Getting Started" section featuring the automated setup script
- Provides clear instructions for making script executable and running it
- Maintains manual setup option with reference to script for exact versions

[TKN-683] Add `setup.sh` script for local Whirlpools build
