sdk/src/quotes/public/decrease-liquidity-quote.ts, sdk/tests/integration/multi-ix/position_management.test.ts
- Fix incorrect import for ZERO in decrease_liquidity_quote
- Fix incorrect toTx import in position_management.test.ts
- Confirmed that there are no other /sdk dependencies here
=> Fix incorrect imports in the SDK

sdk/src/impl/whirlpool-client-impl.ts
* Fix incorrect fetch of mintA instead of mintB
=> Fix incorrect fetch of mintA instead of mintB

sdk/src/impl/whirlpool-client-impl.ts, sdk/src/whirlpool-client.ts
- Add an option to refresh/not-refresh accounts for WhirlpoolClient
=> Add optional refresh parameter for whirlpoolclient

sdk/src/impl/position-impl.ts, sdk/src/impl/whirlpool-client-impl.ts, sdk/src/impl/whirlpool-impl.ts, sdk/src/whirlpool-client.ts
- Add `getAddress` for Whirlpool & Position helper class
- Add `getFetcher` for WhirlpoolClient helper class
=> Add more helper classes for WhirlpoolClient classes

programs/whirlpool/Cargo.toml
Update anchor sources to git as the ones from cargo were yanked and people can't import it or face a build error.
=> Update anchor sources to git

sdk/src/impl/whirlpool-impl.ts, sdk/src/instructions/decrease-liquidity-ix.ts, sdk/src/instructions/increase-liquidity-ix.ts, sdk/src/quotes/public/decrease-liquidity-quote.ts, sdk/src/quotes/public/increase-liquidity-quote.ts
- Previous change to Increase/DecreaseLiquidityInput broke the Increase/DecreaseLiquidityParams
- Add new Increase/DecreaseLiquidityQuote type to add a layer of separation between Params and Quote
=> Fix build errors for increase/decrease liquidity Ix

sdk/package.json, sdk/src/quotes/public/swap-quote.ts, sdk/src/utils/position-util.ts, sdk/src/utils/public/index.ts, sdk/src/utils/public/pool-utils.ts, sdk/src/utils/public/types.ts, sdk/tests/sdk/whirlpools/utils/pool-utils.test.ts, sdk/tests/utils/testDataTypes.ts
- Add util functions to PoolUtil to help identify swap direction & token A/B for token mints
=> Add PoolUtil swap direction & token type util functions

sdk/src/impl/whirlpool-impl.ts, sdk/src/utils/public/tick-utils.ts, sdk/src/whirlpool-client.ts, sdk/tests/sdk/whirlpools/whirlpool-impl.test.ts
- Method will auto-check which tick-array requires initialization
- Will generate a list of initTickArray Ix
- Modify test to send initTickArray + openPosition together
=> Upgrade initTickArrayForTicks for WhirlpoolClient

sdk/src/impl/position-impl.ts, sdk/src/whirlpool-client.ts, sdk/tests/sdk/whirlpools/position-impl.test.ts, sdk/tests/sdk/whirlpools/whirlpool-impl.test.ts
- Change parameter ordering for resolveATA as it is the most important parameter
- Default resolveATA to true. Power users who do not want to ping RPC constantly can manually turn it off
- Fix up some comments
=> Change param ordering for Position's resolveATA 

sdk/package.json, sdk/yarn-error.log
- Add new `swapWithDevFees` functionality
=> Release 0.5.2

sdk/src/impl/whirlpool-client-impl.ts, sdk/src/whirlpool-client.ts
- Provide a new method to fetch many positions in a single RPC call
- On my test branch in Orca UI, verified that this method will return all positions
=> Add getPositions function to WhirlpoolClient

sdk/package.json, sdk/tests/integration/get_pool_prices.test.ts
- bump common-sdk to use AddressUtil.toStrings
- remove .only (test case)
=> Bump common-sdk to v0.1.12

sdk/src/utils/public/tick-utils.ts, sdk/tests/sdk/whirlpools/utils/tick-utils.test.ts
Add a utility function to handle FullRange as it is becoming more and more common.
- ``TickUtil.getFullRangeTickIndex``
- ``TickUtil.isFullRange``
=> add FullRange related util functions

sdk/README.md
Update dependency in readme for SDK.
=> Update sdk README.md to use coral/anchor instead of serum/anchor

sdk/package.json, yarn.lock
Bump common-sdk to pick up latest fix added here:
https://github.com/orca-so/orca-sdks/pull/74
=> Bump common-sdk to 0.5.3

sdk/src/impl/whirlpool-impl.ts
Add the ability to use price slippage based decreaseLiquidityQuote in the close-position function in whirlpoolClient
=> Support price slippage option for decreaseLiquidityQuote in close position

legacy-sdk/whirlpool/src/router/public/router-utils.ts
=> chore: update router-utils.ts

.github/workflows/checks.yml, .github/workflows/docs.yml
Two issues with the script which causes it to fail:
* Did not add the pages configure step
* Upload artifact path was wrong
=> Fix docs github actions deploy script

.github/workflows/publish.yml
=> Fix automatic version setting in gh actions publish workflow

.github/actions/version/action.yml, .github/workflows/publish.yml
* Small bug using `jq` when no matching keys are found
* Ordering of the deploys need to be correct
=> Fix a small bug in version setting script

docs/whirlpool/docs/03-Whirlpools SDK/01-Environment Setup.md
Added a section to the "Environment Setup" documentation explaining how to configure the Whirlpools SDK for different networks/WhirlpoolConfigs.
=> Add documentation for configuring Whirlpools SDK for different networks/WhirlpoolConfigs

ts-sdk/whirlpool/README.md
Add README for high-level TS SDK to be published on npmjs.
=> Add README for high-level TS SDK

docs/whirlpool/docs/04-Legacy SDK/05-Tutorial: Tour de Whirlpool/04-Check Balances.md, docs/whirlpool/docs/04-Legacy SDK/05-Tutorial: Tour de Whirlpool/05-Send Tokens.md
Read more: https://github.com/solana-labs/solana-web3.js/issues/3498
=> Update URLs to point specifically to v1 of the `@solana/web3.js` docs

legacy-sdk/whirlpool/src/types/public/constants.ts
=> Add Whirlpools config for eclipse

legacy-sdk/whirlpool/package.json
=> Increase version of legacy sdk

docs/whirlpool/docs/03-Whirlpools SDKs/03-Whirlpools/03-Whirlpool Management/01-Create Pool.md, ts-sdk/whirlpool/src/createPool.ts, ts-sdk/whirlpool/src/increaseLiquidity.ts, ts-sdk/whirlpool/tests/createPool.test.ts
**Title**
increaseLiquidity.ts enhancements
**Details**
- Add uniform naming for initializationCost.
- Fix return types for increaseLiquidity and openPosition
- Fix rent calculation.
- Add tickindex ordering
=> increaseLiquidity.ts enhancements

README.md
=> Spelling fix in README.md

.github/actions/anchor/action.yml
=> Don't fail if nothing to cache GH Actions

examples/rust-sdk/whirlpool_repositioning_bot/README.md, examples/rust-sdk/whirlpool_repositioning_bot/src/main.rs, examples/rust-sdk/whirlpool_repositioning_bot/src/position_manager.rs
- Fix README
- change `_price_sqrt` to `_sqrt_price`
- Update console logging
=> Clean up lp bot

docs/whirlpool/docs/03-Whirlpools SDKs/01-Whirlpools/06-Send Transaction.mdx
Fix sorting of priority fees in Send Transaction doc
=> Docs: Fix priority fee sorting

.github/dependabot.yml
=> Fix an issue with dependabot config

.github/workflows/publish.yml
Path to find the idl file was incorrect
=> Fix tagging idl to release in publish action

ts-sdk/whirlpool/tests/swap.test.ts, ts-sdk/whirlpool/tests/utils/program.ts
=> Add tests for swap

.changeset/giant-deers-pretend.md, .changeset/serious-parents-heal.md, docs/whirlpool/docusaurus.config.js, docs/whirlpool/static/index.css, rust-sdk/whirlpool/src/position.rs
- Update example rust docs for `fetch_positions_for_owner`
- Update navbar to include API
- remove 'external-link' icon
=> Update docs. Add changesets.

.changeset/early-plums-smoke.md, .changeset/famous-drinks-press.md, docs/legacy/typedoc.json, scripts/publish-docs
=> Fix a bug where certain pages in typescript docs would return a 404

legacy-sdk/common/package.json, nx.json
=> Fix publish gh actions script

.github/workflows/publish.yml
=> Publish to npm fixes

scripts/deploy-cargo, scripts/deploy-docs, scripts/deploy-npm
=> Fix publishing docs to gh pages

.github/workflows/publish.yml
=> Fix publishing to github pages

.changeset/smart-eagles-yell.md, legacy-sdk/integration/package.json
=> Bump tx-sender to 1.0

.changeset/eighty-plums-invent.md, Cargo.lock, docs/rust/Cargo.lock, docs/whirlpool/docs/02-Architecture Overview/05-Whirlpool Fees.md, docs/whirlpool/docs/03-SDKs/03-Whirlpool Management/01-Create Pool.mdx, docs/whirlpool/docs/03-SDKs/04-Position Management/01-Open Position.mdx, docs/whirlpool/docs/03-SDKs/04-Position Management/02-Adjust Liquidity.mdx, docs/whirlpool/docs/03-SDKs/04-Position Management/03-Harvest.mdx, docs/whirlpool/docs/03-SDKs/04-Position Management/04-Close Position.mdx, docs/whirlpool/docs/03-SDKs/05-Trade.mdx, docs/whirlpool/docs/05-Examples/02-CPI.mdx, docs/whirlpool/docusaurus.config.js, examples/rust-sdk/whirlpool_repositioning_bot/Cargo.lock, rust-sdk/client/Cargo.lock, rust-sdk/core/Cargo.lock, rust-sdk/whirlpool/Cargo.lock, ts-sdk/core/Cargo.lock
This PR:
- Adds an Adaptive Fees Math explainer to the `Whirlpool Fees` doc
- Fixes basic usage examples related to `actions` in our Kit SDK
=> Add Adaptive Fees math explainer + doc fixes

.changeset/plenty-pugs-peel.md, docs/whirlpool/docs/04-API.mdx
- Point API page to https://api.orca.so/docs
=> INF-899 - Update API documentation link

.changeset/weak-experts-dress.md, legacy-sdk/cli/README.md, legacy-sdk/cli/src/commands/initialize_adaptive_fee_tier.ts, legacy-sdk/cli/src/commands/initialize_whirlpool.ts, legacy-sdk/cli/src/commands/set_initialize_pool_authority.ts
There are several instructions for AdaptiveFee feature.
In this PR, the most important 3 instructions will be coverred.
- initialize_adaptive_fee_tier
- initialize_pool_with_adaptive_fee
- set_initialize_pool_authority
=> Add AdaptiveFee related CLI command
